version: '3'
services:
  nodejs:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=dba
      - DB_NAME=cloudDB
      - DB_PORT=5432
    volumes:
      - ./uploads:/app/uploads
    command: >
      sh -c "
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      node app.js
      "

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dba
      POSTGRES_DB: cloudDB
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d cloudDB"]
      interval: 10s
      timeout: 5s
      retries: 5


  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodejs
