version: '3'
services:
  nodejs:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=dba
      - DB_NAME=cloudDB
      - DB_PORT=5432

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dba
      POSTGRES_DB: cloudDB
    ports:
      - "5432:5432"


  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodejs
